CREATE DATABASE DBFORGITHUB
GO
USE DBFORGITHUB
GO
CREATE TABLE DBTestTable
(
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Text] NVARCHAR(MAX) NOT NULL CHECK(LEN([Text])>5),
[Date] DATETIME
);


INSERT INTO DBTestTable
VALUES
('TEXT_1'),
('TEXT_2'),
('TEXT_3'),
('TEXT_4'),
('TEXT_5')
